export const DEFAULT_SCHEDULED_WORKING_DAYS = 21;

export const EMPLOYEE_CATEGORY = {
  MONTHLY_BASIC: "MONTHLY_BASIC",
  DAILY_BASIC: "DAILY_BASIC",
  HOURLY_BASIC: "HOURLY_BASIC",
};
export const MONTHLY_BASIC_CATEGORY = {
  EXECUTIVE: "EXECUTIVE",
  NON_EXECUTIVE: "NON_EXECUTIVE",
};

export const config = {
  DEFAULT_SCHEDULED_WORKING_DAYS,
  EMPLOYEE_CATEGORY,
  MONTHLY_BASIC_CATEGORY,
};
